[deps]
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[sources]
UnicodePlots = {path = "../UnicodePlots"}
