annotate_untyped_fields_with_any = false
short_to_long_function_def = false
long_to_short_function_def = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
whitespace_in_kwargs = true
always_use_return = false
conditional_to_if = false
align_struct_field = true
align_conditional = true
align_assignment = true
align_pair_arrow = true
import_to_using = false
