# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^assets/references_
    -   id: end-of-file-fixer
        exclude: ^assets/references_
    -   id: check-toml
    -   id: check-yaml
    # -   id: check-added-large-files
-   repo: https://github.com/fredrikekre/runic-pre-commit
    rev: v2.0.1
    hooks:
      - id: runic
