name = "UnicodePlots"
uuid = "b8865327-cd53-5732-bb35-84acbb429228"
license = "MIT"
desc = "Unicode-based scientific plotting for working in the terminal"
authors = ["Christof Stocker <stocker.christof@gmail.com>"]
version = "1.2.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Crayons = "4.0"
StatsBase = "0.32"
julia = "1"

[extras]
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReferenceTests"]
